name: Selenium TestNG CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1

      - uses: nanasess/setup-chromedriver@v2

      - name: Run Tests
        run: mvn test -D test=tests.PZU.**
