name: Java Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Set up Chrome & ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Verify ChromeDriver Installation
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run Selenium Tests
        run: mvn test
        env:
          DISPLAY: ":99.0"

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/*.xml
